# Generated by Django 2.0.1 on 2018-02-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('birthday_type', models.SmallIntegerField(default=('0', 'NULL'), verbose_name=(('0', 'NULL'), ('1', '阳历'), ('2', '农历')))),
                ('birthday', models.DateTimeField()),
                ('avatar_url', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=45)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': '生日信息',
                'db_table': 'birthday_logs',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('birthday_type', models.SmallIntegerField(default=('0', 'NULL'), verbose_name=(('0', 'NULL'), ('1', '阳历'), ('2', '农历')))),
                ('birthday', models.DateTimeField()),
                ('avatar_url', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=45)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': '用户表',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='WechatUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=45)),
                ('avatar_url', models.CharField(max_length=2000)),
                ('gender', models.SmallIntegerField(default=('0', 'NULL'), verbose_name=(('0', 'NULL'), ('1', 'MALE'), ('2', 'FEMALE')))),
                ('city', models.CharField(max_length=45)),
                ('province', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
                ('language', models.CharField(max_length=45)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': '用户微信信息',
                'db_table': 'wechat_users',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='wechat_user_id',
            field=models.ForeignKey(on_delete=True, to='yuanyuan_app.WechatUsers'),
        ),
        migrations.AddField(
            model_name='birthdaylogs',
            name='user_id',
            field=models.ForeignKey(on_delete=True, to='yuanyuan_app.Users'),
        ),
    ]
